# Generated by Django 4.2.3 on 2023-07-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
